name : CI/CD Deployment

on :
  push :
    branches :
      - main

jobs :
  build-and-deploy :
    runs-on : ubuntu-latest
    
    steps:
      -name : Checkout Code
      uses : actions/checkout@v3

      -name : Set up Node.jobs
      uses : actions/setup-node@v3
      with:
        node-version: '18'
      
      -name : Build Docker Image
      run: docker build -t cicd-demo .

      -name: Run Docker Container (Mock)
      run: echo "Would run container here in real deploy"

        # ğŸ” You can later replace the run step with a real deployment to 
        # Heroku, AWS, Render, etc.